version: '3'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - QDRANT_URL=
      - QDRANT_API_KEY=
      - COLLECTION_NAME=code-memories
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - TOOL_STORE_DESCRIPTION=Store reusable code snippets for later retrieval. The 'information' parameter should contain a natural language description of what the code does, while the actual code should be included in the 'metadata' parameter as a 'code' property. The value of 'metadata' is a Python dictionary with strings as keys. Use this whenever you generate some code snippet.
      - TOOL_FIND_DESCRIPTION=Search for relevant code snippets based on natural language descriptions. The 'query' parameter should describe what you're looking for, and the tool will return the most relevant code snippets. Use this when you need to find existing code snippets for reuse or reference.
    # Enable TTY and STDIN to keep the container running and allow interaction
    tty: true
    stdin_open: true
    # Restart the container if it crashes
    restart: unless-stopped
